#!/usr/bin/env python3
"""
Stage 4: Assemble the deepdive report.

This script is a SCAFFOLD. It reads the artifacts from Stages 1-3
(paper_claims.json, innovation_analysis.json if exists, figure_analysis.json,
code_map.json) and extracts the relevant code snippets into one place, then
generates a skeleton report file with sections pre-filled.

The actual analytic writing — comparing paper to code, identifying hidden
details, calling out discrepancies — is Claude's job. This script just
assembles raw material and the template.

Usage:
    python deep_compare.py \
        --claims paper_claims.json \
        --code-map code_map.json \
        [--figures figure_analysis.json] \
        [--out deepdive_report.md]

Output:
    - deepdive_report.md: skeleton report with template sections and extracted
      code snippets, ready for Claude to fill in analysis.
    - comparison_bundle.json: raw material combined into one JSON for Claude
      to work from.
"""

import argparse
import json
import sys
from pathlib import Path


def read_code_window(file_path: str, start_line: int, end_line: int,
                     context: int = 3) -> str:
    """Read a window of code, with a few lines of context."""
    try:
        lines = Path(file_path).read_text(encoding="utf-8",
                                          errors="replace").splitlines()
    except Exception as e:
        return f"[could not read {file_path}: {e}]"
    s = max(0, start_line - 1 - context)
    e = min(len(lines), end_line + context)
    out = []
    for i in range(s, e):
        marker = ">>>" if (start_line - 1) <= i < end_line else "   "
        out.append(f"{marker} {i + 1:4d}  {lines[i]}")
    return "\n".join(out)


def assemble_bundle(
    claims: dict,
    code_map: dict,
    figures: dict | None,
) -> dict:
    """Combine all artifacts into one bundle for Claude."""
    innovations = claims.get("innovations", [])
    code_inns = {x.get("id"): x for x in code_map.get("innovations", [])}

    bundle = {
        "paper_source": claims.get("pdf_path"),
        "repo_source": code_map.get("repo_path"),
        "innovations": [],
        "figures": figures.get("figures_analyzed", []) if figures else [],
        "repo_inventory": code_map.get("repo_inventory", {}),
    }

    for inn in innovations:
        inn_id = inn.get("id")
        code_info = code_inns.get(inn_id, {})
        resolved = code_info.get("resolved_location", {})

        code_window = None
        if resolved.get("file"):
            code_window = read_code_window(
                resolved["file"],
                resolved.get("start_line", 1),
                resolved.get("end_line", resolved.get("start_line", 1) + 20),
                context=5,
            )

        bundle["innovations"].append({
            "paper_side": inn,
            "code_side": {
                "resolved_location": resolved,
                "code_window": code_window,
                "all_hits": code_info.get("hits_by_term", {}),
            },
        })

    return bundle


def generate_skeleton_report(bundle: dict, report_path: Path):
    """Create a markdown file with template sections pre-filled per innovation."""
    lines = []
    lines.append("# Deepdive Report (SKELETON)")
    lines.append("")
    lines.append(f"**Paper source:** {bundle.get('paper_source', '?')}")
    lines.append(f"**Repo source:** {bundle.get('repo_source', '?')}")
    lines.append("")
    lines.append(
        "> This is a skeleton generated by `deep_compare.py`. Claude should "
        "fill in each section following `references/report_template.md` and "
        "using `references/hidden_details_checklist.md` for the 'Details the "
        "paper omits' subsections."
    )
    lines.append("")
    lines.append("## TL;DR")
    lines.append("")
    lines.append("*(Claude to fill: 3-5 sentences summarizing innovations and "
                 "most surprising paper-vs-code findings.)*")
    lines.append("")
    lines.append("## Setup")
    lines.append("")
    lines.append("*(Claude to fill: paper version, code commit, framework, caveats.)*")
    lines.append("")

    for i, item in enumerate(bundle.get("innovations", []), start=1):
        paper = item["paper_side"]
        code = item["code_side"]

        lines.append(f"## Innovation {i}: {paper.get('name', '(unnamed)')}")
        lines.append("")
        lines.append(f"**Paper location:** {paper.get('location_in_paper', {})}")
        lines.append(
            f"**Code location:** {code.get('resolved_location', {})}"
        )
        lines.append(f"**Type:** {paper.get('type', '?')}")
        lines.append("")
        lines.append("### What the paper claims")
        lines.append("")
        lines.append(f"*(Claude: write 1-2 paragraphs based on {paper.get('name')}'s "
                     f"paper description. The claimed benefit is: "
                     f"'{paper.get('claimed_benefit', 'N/A')}'.)*")
        lines.append("")
        lines.append("### What the code actually does")
        lines.append("")
        if code.get("code_window"):
            lines.append("```")
            lines.append(code["code_window"])
            lines.append("```")
        else:
            lines.append("*(No resolved code location. Claude: either find it "
                         "by reading the candidate hits, or mark as 'not found "
                         "in public code'.)*")
        lines.append("")
        lines.append("### Details the paper omits")
        lines.append("")
        lines.append(
            "*(Claude: walk through `references/hidden_details_checklist.md`. "
            "For each applicable category — initialization, normalization, "
            "activation, attention details, dropout, numerical stabilizers, "
            "train/inference branching, loss details, optimizer, data — look "
            "at the code and report concrete values with file:line citations. "
            "This is the highest-value section.)*"
        )
        lines.append("")
        lines.append("### Paper-code discrepancies")
        lines.append("")
        lines.append("*(Claude: list any. For each: paper location, code location, "
                     "likely explanation, likely impact. If none, write 'None found.')*")
        lines.append("")
        lines.append("### Reproduction checklist")
        lines.append("")
        lines.append("*(Claude: concrete actionable items for reproducing this innovation.)*")
        lines.append("")
        lines.append("### Confidence")
        lines.append("")
        lines.append("*(Claude: mark which findings are HIGH/MEDIUM/LOW confidence.)*")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## Cross-cutting findings")
    lines.append("")
    lines.append("*(Claude: training tricks, data pipeline, precision, EMA, "
                 "optimizer details that span multiple innovations.)*")
    lines.append("")
    lines.append("## Open questions")
    lines.append("")
    lines.append("*(Claude: things neither paper nor code resolves. Honest open "
                 "questions > fabricated answers.)*")
    lines.append("")

    report_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--claims", type=Path, required=True)
    parser.add_argument("--code-map", type=Path, required=True)
    parser.add_argument("--figures", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=Path("deepdive_report.md"))
    parser.add_argument("--bundle-out", type=Path,
                        default=Path("comparison_bundle.json"))
    args = parser.parse_args()

    for p in [args.claims, args.code_map]:
        if not p.exists():
            print(f"ERROR: {p} not found", file=sys.stderr)
            sys.exit(1)

    claims = json.loads(args.claims.read_text())
    code_map = json.loads(args.code_map.read_text())
    figures = None
    if args.figures and args.figures.exists():
        figures = json.loads(args.figures.read_text())

    bundle = assemble_bundle(claims, code_map, figures)
    args.bundle_out.write_text(
        json.dumps(bundle, indent=2, ensure_ascii=False)
    )
    print(f"Wrote bundle to {args.bundle_out}", file=sys.stderr)

    generate_skeleton_report(bundle, args.out)
    print(f"Wrote skeleton report to {args.out}", file=sys.stderr)
    print(
        "\nNext: Claude opens the skeleton report and fills each section, "
        "referring to the bundle JSON, reading more code as needed, and "
        "consulting hidden_details_checklist.md for the omitted-details "
        "sections.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
