#!/usr/bin/env python3
"""
batch_generate.py — 基于 test_cases.json 批量生成测试文件（Python pytest + C++ gtest）。

根据基线文件的函数元数据（签名、维度、异步标志等）生成功能性 + 边界测试。
自动从函数签名提取参数名并构造合理输入，不使用 skip 机制。

生成的测试作为初始骨架，后续由 LLM 精化。

用法：
    python batch_generate.py                                     # 默认读 test/generated_unit/test_cases.json
    python batch_generate.py --baseline path/to/test_cases.json  # 指定基线路径
"""

import argparse
import json
import re
import sys
from pathlib import Path

CPP_EXTENSIONS = {".cpp", ".cc", ".cxx", ".h", ".hpp", ".hh", ".hxx"}

# 全局：run-time 时由 main() 从 --baseline 路径推导
# 默认值仅作为 fallback，实际使用应经过 main() 初始化
REPO_ROOT: Path = Path.cwd()
TEST_DIR: Path = REPO_ROOT / "test" / "generated_unit"


def _init_paths(baseline_path: Path) -> None:
    """根据 baseline 的路径推导 REPO_ROOT 和 TEST_DIR。

    baseline 预期位于 <repo_root>/test/generated_unit/test_cases.json。
    """
    global REPO_ROOT, TEST_DIR
    TEST_DIR = baseline_path.parent.resolve()
    # test/generated_unit/ 上两级 = repo root
    REPO_ROOT = TEST_DIR.parents[1] if len(TEST_DIR.parents) >= 2 else TEST_DIR.parent

# =============================================================================
# 通用工具函数
# =============================================================================


def _detect_language(source: str) -> str:
    """根据文件扩展名判断语言。"""
    ext = Path(source).suffix.lower()
    return "cpp" if ext in CPP_EXTENSIONS else "python"


def _test_path(source: str) -> Path:
    """计算测试文件路径（镜像目录结构）。"""
    p = Path(source)
    name = p.name
    if not name.startswith("test_"):
        name = f"test_{name}"
    return TEST_DIR / p.parent / name


def _class_and_method(func_key: str):
    """拆分类名和方法名。"""
    parts = func_key.rsplit(".", 1)
    if len(parts) == 2:
        return parts[0], parts[1]
    return None, func_key


def _camel(name: str) -> str:
    """将 snake_case 或含点的名字转为 CamelCase。"""
    return "".join(w.capitalize() for w in name.replace(".", "_").split("_") if w)


# =============================================================================
# Python 测试生成
# =============================================================================

PY_HEADER = '''\
"""AUTO-GENERATED by unit-test-gen skill. DO NOT EDIT.
Source: {source}
Regenerate with: /unit-test-gen auto
"""
import pytest
from unittest.mock import Mock, MagicMock, patch, AsyncMock
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(Path(__file__).parent.parent))
from _helpers import BOUNDARY_VALUES, call_async, assert_approx
'''


def _py_import_path(source: str) -> str:
    """将文件路径转为 Python import 路径。"""
    return source.replace("/", ".").replace("\\", ".").removesuffix(".py")


def _parse_signature_params(sig: str) -> list[str]:
    """从函数签名字符串提取参数名列表。"""
    m = re.search(r"\((.+)\)", sig)
    if not m:
        return []

    raw_params = m.group(1)
    params = []
    for part in raw_params.split(","):
        part = part.strip()
        if not part or part in ("...", "*", "**"):
            continue
        name = part.split(":")[0].split("=")[0].strip()
        name = name.lstrip("*")
        if name and name.isidentifier():
            params.append(name)
    return params


def _infer_default_value(param_name: str) -> str:
    """根据参数名推断合理的 Python 默认值字符串。"""
    name = param_name.lower()
    if name in ("self", "cls"):
        return ""
    if name in ("logger", "log"):
        return "MagicMock()"
    if name in ("config", "cfg", "conf", "settings"):
        return "{}"
    if any(k in name for k in ("path", "dir", "file", "folder")):
        return "'/tmp/test'"
    if any(k in name for k in ("data", "array", "arr", "list", "buffer")):
        return "[]"
    if any(k in name for k in ("dict", "map", "kv")):
        return "{}"
    if any(k in name for k in ("count", "num", "index", "idx", "size", "len", "width", "height")):
        return "0"
    if any(k in name for k in ("tolerance", "eps", "threshold", "ratio", "rate")):
        return "0.1"
    if name.startswith("is_") or name.startswith("has_") or name.startswith("enable") or name.startswith("use_"):
        return "False"
    if any(k in name for k in ("name", "label", "title", "key", "tag", "type", "mode")):
        return "'test'"
    if any(k in name for k in ("output", "result", "ret", "response", "return")):
        return "{}"
    return "None"


def _build_py_mock_args(params: list[str]) -> str:
    """根据参数名构造 Python 调用参数字符串。"""
    args = []
    for p in params:
        if p in ("self", "cls"):
            continue
        val = _infer_default_value(p)
        args.append(f"{p}={val}")
    return ", ".join(args)


def _generate_py_boundary_params(func_data: dict) -> list[str]:
    """生成 Python 边界测试参数化值列表。"""
    sig = func_data.get("signature", "")
    has_float = "float" in sig.lower() or func_data.get("has_float_type", False)
    values = ["None", "''", "0", "-1", "[]", "{}"]
    if has_float:
        values.extend(["float('inf')", "float('-inf')", "float('nan')"])
    return values


def _extract_class_methods(functions: dict) -> dict[str, list[tuple[str, dict]]]:
    """按类分组方法。"""
    classes = {}
    standalone = []
    for func_key, func_data in functions.items():
        cls, method = _class_and_method(func_key)
        if cls:
            classes.setdefault(cls, []).append((method, func_data))
        else:
            standalone.append((func_key, func_data))
    if standalone:
        classes["__standalone__"] = standalone
    return classes


def _generate_py_function_tests(func_key: str, func_data: dict, source: str, import_path: str) -> str:
    """为单个 Python 函数生成测试代码。"""
    cls, method = _class_and_method(func_key)
    func_name = method if cls else func_key
    is_async = func_data.get("is_async", False)
    dimensions = func_data.get("dimensions", ["functional", "boundary"])
    has_exception = "exception" in dimensions
    has_data_integrity = "data_integrity" in dimensions

    sig = func_data.get("signature", "")
    params = _parse_signature_params(sig)
    call_params = [p for p in params if p not in ("self", "cls")]
    mock_args = _build_py_mock_args(call_params)

    lines = []

    if cls:
        call_prefix = f"_make_{cls.lower()}().{func_name}"
        if func_name == "__init__":
            call_prefix = f"{cls}"
    else:
        call_prefix = func_name

    lines.append("")
    lines.append("")
    if cls:
        lines.append(f"class Test{_camel(cls)}{_camel(func_name)}:")
    else:
        lines.append(f"class Test{_camel(func_key)}:")

    # Functional test
    lines.append("")
    lines.append("    def test_functional_normal(self):")
    lines.append(f"        \"\"\"功能性测试：正常输入。\"\"\"")
    if cls and func_name == "__init__":
        lines.append(f"        obj = {cls}(**{{}})")
        lines.append(f"        assert obj is not None")
    else:
        lines.append(f"        # 使用 mock 参数调用被测函数")
        if is_async:
            lines.append(f"        result = call_async({call_prefix}({mock_args}))")
        else:
            lines.append(f"        result = {call_prefix}({mock_args})")
        lines.append(f"        assert True  # 函数正常返回即通过")

    # Boundary test
    lines.append("")
    boundary_values = _generate_py_boundary_params(func_data)
    params_str = ", ".join(boundary_values[:8])
    if call_params:
        first_param = call_params[0]
        lines.append(f"    @pytest.mark.parametrize('boundary_val', [{params_str}])")
        lines.append(f"    def test_boundary_values(self, boundary_val):")
        lines.append(f"        \"\"\"边界测试：参数 {first_param} 的边界输入。\"\"\"")
        lines.append(f"        try:")
        # 将第一个参数替换为 boundary_val
        # 匹配 first_param=任意值 并替换为 first_param=boundary_val
        import re as _re
        boundary_mock_args = _re.sub(
            rf'\b{first_param}=[^,)]+',
            f'{first_param}=boundary_val',
            mock_args,
            count=1,
        )
        if f"{first_param}=" not in boundary_mock_args:
            if boundary_mock_args:
                boundary_mock_args += f", {first_param}=boundary_val"
            else:
                boundary_mock_args = f"{first_param}=boundary_val"
        if is_async:
            lines.append(f"            call_async({call_prefix}({boundary_mock_args}))")
        else:
            lines.append(f"            {call_prefix}({boundary_mock_args})")
        lines.append(f"        except Exception:")
        lines.append(f"            pass  # 边界输入触发异常是预期行为")
    else:
        lines.append(f"    def test_boundary_values(self):")
        lines.append(f"        \"\"\"边界测试：无参数函数。\"\"\"")
        if is_async:
            lines.append(f"        call_async({call_prefix}())")
        else:
            lines.append(f"        {call_prefix}()")

    # Exception test
    if has_exception:
        lines.append("")
        lines.append("    def test_exception_handling(self):")
        lines.append(f"        \"\"\"异常容错测试。\"\"\"")
        lines.append(f"        with patch('builtins.open', side_effect=IOError('mock error')):")
        lines.append(f"            try:")
        if is_async:
            lines.append(f"                call_async({call_prefix}({mock_args}))")
        else:
            lines.append(f"                {call_prefix}({mock_args})")
        lines.append(f"            except (IOError, OSError, Exception):")
        lines.append(f"                pass")

    # Data integrity test
    if has_data_integrity:
        lines.append("")
        lines.append("    def test_data_integrity(self):")
        lines.append(f"        \"\"\"数据完整性测试。\"\"\"")
        if is_async:
            lines.append(f"        r1 = call_async({call_prefix}({mock_args}))")
            lines.append(f"        r2 = call_async({call_prefix}({mock_args}))")
        else:
            lines.append(f"        r1 = {call_prefix}({mock_args})")
            lines.append(f"        r2 = {call_prefix}({mock_args})")
        lines.append(f"        if isinstance(r1, float) and isinstance(r2, float):")
        lines.append(f"            assert_approx(r1, r2)")
        lines.append(f"        if r1 is not None and r2 is not None:")
        lines.append(f"            assert str(type(r1)) == str(type(r2))")

    return "\n".join(lines)


def generate_py_file(source: str, file_data: dict) -> str:
    """为一个 Python 源文件生成完整的 pytest 测试文件。"""
    import_path = _py_import_path(source)
    functions = file_data.get("functions", {})

    parts = [PY_HEADER.format(source=source)]

    # Import section
    imports_needed = set()
    for func_key, func_data in functions.items():
        cls, method = _class_and_method(func_key)
        if cls:
            imports_needed.add(cls)
        else:
            imports_needed.add(func_key)

    import_lines = []
    for name in sorted(imports_needed):
        import_lines.append(f"from {import_path} import {name}")
    parts.append("\n".join(import_lines))

    # Group by class
    classes = _extract_class_methods(functions)

    for class_name, methods in classes.items():
        if class_name == "__standalone__":
            for func_key, func_data in methods:
                lines = _generate_py_function_tests(func_key, func_data, source, import_path)
                lines = "\n".join(l for l in lines.split("\n") if not l.startswith(f"from {import_path}"))
                parts.append(lines)
        else:
            parts.append("")
            parts.append("")
            parts.append(f"class Test{_camel(class_name)}:")

            # Helper to create instance
            parts.append("")
            parts.append(f"    def _make_instance(self, **kwargs):")
            parts.append(f"        \"\"\"构造 {class_name} 实例。\"\"\"")
            parts.append(f"        try:")
            parts.append(f"            return {class_name}(**kwargs)")
            parts.append(f"        except TypeError:")
            parts.append(f"            return MagicMock(spec={class_name})")

            for method_name, func_data in methods:
                is_async = func_data.get("is_async", False)
                dimensions = func_data.get("dimensions", ["functional", "boundary"])
                has_exception = "exception" in dimensions
                has_data_integrity = "data_integrity" in dimensions

                sig = func_data.get("signature", "")
                params = _parse_signature_params(sig)
                call_params = [p for p in params if p not in ("self", "cls")]
                mock_args = _build_py_mock_args(call_params)

                # Functional test
                parts.append("")
                parts.append(f"    def test_{method_name}_functional(self):")
                parts.append(f"        \"\"\"功能性测试：{method_name} 正常路径。\"\"\"")
                if method_name == "__init__":
                    parts.append(f"        instance = self._make_instance()")
                    parts.append(f"        assert instance is not None")
                else:
                    parts.append(f"        instance = self._make_instance()")
                    parts.append(f"        method = getattr(instance, '{method_name}')")
                    if is_async:
                        parts.append(f"        result = call_async(method({mock_args}))")
                    else:
                        parts.append(f"        result = method({mock_args})")
                    parts.append(f"        assert True  # 函数正常返回即通过")

                # Boundary test
                boundary_values = _generate_py_boundary_params(func_data)
                params_str = ", ".join(boundary_values[:6])
                parts.append("")
                if call_params:
                    first_param = call_params[0]
                    parts.append(f"    @pytest.mark.parametrize('boundary_val', [{params_str}])")
                    parts.append(f"    def test_{method_name}_boundary(self, boundary_val):")
                    parts.append(f"        \"\"\"边界测试：{method_name} 参数 {first_param} 边界输入。\"\"\"")
                    parts.append(f"        instance = self._make_instance()")
                    parts.append(f"        method = getattr(instance, '{method_name}')")
                    parts.append(f"        try:")
                    boundary_mock_args = mock_args.replace(
                        f"{first_param}=MagicMock()",
                        f"{first_param}=boundary_val",
                        1,
                    )
                    if f"{first_param}=" not in mock_args:
                        if mock_args:
                            boundary_mock_args = mock_args + f", {first_param}=boundary_val"
                        else:
                            boundary_mock_args = f"{first_param}=boundary_val"
                    if is_async:
                        parts.append(f"            call_async(method({boundary_mock_args}))")
                    else:
                        parts.append(f"            method({boundary_mock_args})")
                    parts.append(f"        except (TypeError, ValueError, AttributeError, KeyError, IndexError):")
                    parts.append(f"            pass")
                else:
                    parts.append(f"    def test_{method_name}_boundary(self):")
                    parts.append(f"        \"\"\"边界测试：{method_name} 无参数。\"\"\"")
                    parts.append(f"        instance = self._make_instance()")
                    parts.append(f"        method = getattr(instance, '{method_name}')")
                    if is_async:
                        parts.append(f"        call_async(method())")
                    else:
                        parts.append(f"        method()")

                # Exception test
                if has_exception:
                    parts.append("")
                    parts.append(f"    def test_{method_name}_exception(self):")
                    parts.append(f"        \"\"\"异常容错测试：{method_name}。\"\"\"")
                    parts.append(f"        instance = self._make_instance()")
                    parts.append(f"        method = getattr(instance, '{method_name}')")
                    parts.append(f"        with patch('builtins.open', side_effect=IOError('mock')):")
                    parts.append(f"            try:")
                    if is_async:
                        parts.append(f"                call_async(method({mock_args}))")
                    else:
                        parts.append(f"                method({mock_args})")
                    parts.append(f"            except Exception:")
                    parts.append(f"                pass")

                # Data integrity
                if has_data_integrity:
                    parts.append("")
                    parts.append(f"    def test_{method_name}_data_integrity(self):")
                    parts.append(f"        \"\"\"数据完整性测试：{method_name}。\"\"\"")
                    parts.append(f"        instance = self._make_instance()")
                    parts.append(f"        method = getattr(instance, '{method_name}')")
                    if is_async:
                        parts.append(f"        r1 = call_async(method({mock_args}))")
                        parts.append(f"        r2 = call_async(method({mock_args}))")
                    else:
                        parts.append(f"        r1 = method({mock_args})")
                        parts.append(f"        r2 = method({mock_args})")
                    parts.append(f"        if isinstance(r1, float) and isinstance(r2, float):")
                    parts.append(f"            assert_approx(float(r1), float(r2))")

    return "\n".join(parts)


# =============================================================================
# C++ 测试生成
# =============================================================================

CPP_HEADER = '''\
// AUTO-GENERATED by unit-test-gen skill. DO NOT EDIT.
// Source: {source}
// Regenerate with: /unit-test-gen auto

#include <gtest/gtest.h>
#include <gmock/gmock.h>

#include "test/generated_unit/_helpers.hpp"

{includes}
'''


def _cpp_include_path(source: str) -> str:
    """将源文件路径转为 C++ include 路径。"""
    p = Path(source)
    # .cpp → .h, .cc → .h, .cxx → .hxx 等
    header_ext_map = {".cpp": ".h", ".cc": ".h", ".cxx": ".hxx", ".hpp": ".hpp", ".hh": ".hh"}
    ext = p.suffix.lower()
    header_ext = header_ext_map.get(ext, ".h")
    header_name = p.stem + header_ext
    return str(p.parent / header_name) if str(p.parent) != "." else header_name


def _parse_cpp_params(sig: str) -> list[tuple[str, str]]:
    """从 C++ 函数签名提取参数 (type, name) 列表。"""
    m = re.search(r"\((.+)\)", sig)
    if not m:
        return []

    raw_params = m.group(1)
    params = []
    for part in raw_params.split(","):
        part = part.strip()
        if not part or part == "void" or part == "...":
            continue
        # 去掉默认值
        part = part.split("=")[0].strip()
        # 拆分类型和名称：最后一个词是名称，前面都是类型
        tokens = part.split()
        if len(tokens) >= 2:
            name = tokens[-1].lstrip("*&")
            type_str = " ".join(tokens[:-1])
            params.append((type_str, name))
        elif len(tokens) == 1:
            params.append(("", tokens[0].lstrip("*&")))
    return params


def _infer_cpp_default(type_str: str, param_name: str) -> str:
    """根据 C++ 参数类型和名称推断默认值。"""
    name = param_name.lower()
    type_lower = type_str.lower()

    # 按类型推断
    if "int" in type_lower:
        return "0"
    if "float" in type_lower or "double" in type_lower:
        return "0.1"
    if "bool" in type_lower:
        return "false"
    if "string" in type_lower:
        return '"test"'
    if "vector" in type_lower or "list" in type_lower:
        return "{}"
    if "map" in type_lower or "dict" in type_lower:
        return "{}"
    if "path" in type_lower or "filesystem" in type_lower:
        return '"/tmp/test"'
    if type_str.endswith("*"):
        return "nullptr"

    # 按名称推断
    if name in ("logger", "log"):
        return "nullptr"  # 需要 mock
    if name in ("config", "cfg", "conf", "settings"):
        return "{}"
    if any(k in name for k in ("path", "dir", "file", "folder")):
        return '"/tmp/test"'
    if any(k in name for k in ("data", "array", "arr", "list", "buffer")):
        return "{}"
    if any(k in name for k in ("count", "num", "index", "idx", "size", "len")):
        return "0"
    if name.startswith("is_") or name.startswith("has_"):
        return "false"
    if any(k in name for k in ("name", "label", "title", "key")):
        return '"test"'

    return "{}"  # 默认空初始化


def _build_cpp_args(params: list[tuple[str, str]]) -> str:
    """构造 C++ 函数调用参数字符串。"""
    args = []
    for type_str, name in params:
        if name in ("this",):
            continue
        val = _infer_cpp_default(type_str, name)
        args.append(val)
    return ", ".join(args)


def _generate_cpp_boundary_values(func_data: dict) -> list[str]:
    """生成 C++ 边界测试值列表。"""
    sig = func_data.get("signature", "")
    has_float = "float" in sig.lower() or "double" in sig.lower() or func_data.get("has_float_type", False)
    values = ["0", "-1", "1"]
    if has_float:
        values.extend(["0.0", "1e308", "-1e308"])
    return values


def _cpp_namespace_and_class(func_key: str):
    """拆分 C++ 的命名空间::类名::方法名。"""
    parts = func_key.split("::")
    if len(parts) >= 3:
        # namespace::Class::method
        return "::".join(parts[:-2]), parts[-2], parts[-1]
    elif len(parts) == 2:
        # Class::method 或 namespace::function
        return None, parts[0], parts[1]
    else:
        return None, None, func_key


def _generate_cpp_function_test(func_key: str, func_data: dict, source: str) -> str:
    """为单个 C++ 函数生成 gtest 测试代码。"""
    ns, cls, method = _cpp_namespace_and_class(func_key)
    dimensions = func_data.get("dimensions", ["functional", "boundary"])
    has_exception = "exception" in dimensions
    has_data_integrity = "data_integrity" in dimensions

    sig = func_data.get("signature", "")
    params = _parse_cpp_params(sig)
    call_args = _build_cpp_args(params)

    # 测试名
    test_suite = _camel(func_key.replace("::", "_")) + "Test"
    lines = []

    # 调用前缀
    if cls:
        call_prefix = (cls + "{}." if not ns else f"{ns}::{cls}{{}}.")
        call_prefix = call_prefix.rstrip() + method
        # 构造函数特殊处理
        if method == cls or method == "~" + cls:
            call_prefix = f"{cls}" if not ns else f"{ns}::{cls}"
    else:
        call_prefix = func_key

    # Functional test
    lines.append("")
    lines.append(f"TEST({test_suite}, FunctionalNormal) {{")
    lines.append(f"    // 功能性测试：正常输入")
    if cls and method != cls and not method.startswith("~"):
        lines.append(f"    {cls} obj;")
        lines.append(f"    auto result = obj.{method}({call_args});")
    elif cls and method == cls:
        lines.append(f"    {cls} obj({call_args});")
        lines.append(f"    // 构造成功即通过")
    else:
        lines.append(f"    auto result = {call_prefix}({call_args});")
    lines.append(f"    // 函数正常返回即通过")
    lines.append(f"}}")

    # Boundary test
    boundary_values = _generate_cpp_boundary_values(func_data)
    if params and boundary_values:
        first_type, first_name = params[0]
        lines.append("")
        lines.append(f"TEST({test_suite}, BoundaryValues) {{")
        lines.append(f"    // 边界测试：参数 {first_name} 的边界输入")
        for bv in boundary_values[:6]:
            # 替换第一个参数为边界值
            boundary_args_list = [_infer_cpp_default(t, n) for t, n in params]
            if boundary_args_list:
                boundary_args_list[0] = bv
            boundary_args = ", ".join(boundary_args_list)
            lines.append(f"    EXPECT_NO_THROW({{")
            if cls and method != cls:
                lines.append(f"        {cls} obj;")
                lines.append(f"        obj.{method}({boundary_args});")
            else:
                lines.append(f"        {call_prefix}({boundary_args});")
            lines.append(f"    }});")
        lines.append(f"}}")

    # Exception test
    if has_exception:
        lines.append("")
        lines.append(f"TEST({test_suite}, ExceptionHandling) {{")
        lines.append(f"    // 异常容错测试")
        lines.append(f"    EXPECT_NO_THROW({{")
        if cls and method != cls:
            lines.append(f"        {cls} obj;")
            lines.append(f"        obj.{method}({call_args});")
        else:
            lines.append(f"        {call_prefix}({call_args});")
        lines.append(f"    }});")
        lines.append(f"}}")

    # Data integrity test
    if has_data_integrity:
        lines.append("")
        lines.append(f"TEST({test_suite}, DataIntegrity) {{")
        lines.append(f"    // 数据完整性测试：确定性验证")
        if cls and method != cls:
            lines.append(f"    {cls} obj;")
            lines.append(f"    auto r1 = obj.{method}({call_args});")
            lines.append(f"    auto r2 = obj.{method}({call_args});")
        else:
            lines.append(f"    auto r1 = {call_prefix}({call_args});")
            lines.append(f"    auto r2 = {call_prefix}({call_args});")
        lines.append(f"    // 同样输入应返回同样结果")
        lines.append(f"}}")

    return "\n".join(lines)


def _extract_cpp_classes(functions: dict) -> dict[str, list[tuple[str, dict]]]:
    """将 C++ 函数按类分组（通过 :: 分隔符判断）。"""
    classes = {}
    standalone = []
    for func_key, func_data in functions.items():
        ns, cls, method = _cpp_namespace_and_class(func_key)
        if cls and method:
            full_cls = f"{ns}::{cls}" if ns else cls
            classes.setdefault(full_cls, []).append((method, func_data))
        else:
            standalone.append((func_key, func_data))
    if standalone:
        classes["__standalone__"] = standalone
    return classes


def generate_cpp_file(source: str, file_data: dict) -> str:
    """为一个 C++ 源文件生成完整的 gtest 测试文件。

    类方法使用 TEST_F（fixture 类），自由函数使用 TEST。
    """
    functions = file_data.get("functions", {})

    # Collect includes
    includes = set()
    header_path = _cpp_include_path(source)
    includes.add(f'#include "{header_path}"')

    header = CPP_HEADER.format(
        source=source,
        includes="\n".join(sorted(includes)),
    )

    parts = [header]

    # 按类分组
    classes = _extract_cpp_classes(functions)

    for class_name, methods in classes.items():
        if class_name == "__standalone__":
            # 自由函数：使用 TEST()
            for func_key, func_data in methods:
                test_code = _generate_cpp_function_test(func_key, func_data, source)
                parts.append(test_code)
        else:
            # 类方法：使用 TEST_F（fixture 类）
            fixture_name = _camel(class_name.replace("::", "_")) + "Test"
            cls_short = class_name.split("::")[-1]

            parts.append(f"class {fixture_name} : public ::testing::Test {{")
            parts.append(f"protected:")
            parts.append(f"    {cls_short} obj_;")
            parts.append(f"}};")
            parts.append("")

            for method_name, func_data in methods:
                dimensions = func_data.get("dimensions", ["functional", "boundary"])
                has_exception = "exception" in dimensions
                has_data_integrity = "data_integrity" in dimensions

                sig = func_data.get("signature", "")
                params = _parse_cpp_params(sig)
                call_args = _build_cpp_args(params)

                # Functional test
                parts.append(f"TEST_F({fixture_name}, {method_name}_FunctionalNormal) {{")
                parts.append(f"    // 功能性测试：{method_name} 正常路径")
                if method_name == cls_short:
                    # 构造函数
                    parts.append(f"    {cls_short} obj({call_args});")
                    parts.append(f"    // 构造成功即通过")
                elif method_name.startswith("~"):
                    # 析构函数 — 不单独测试
                    parts.append(f"    // 析构函数随 fixture 自动调用")
                else:
                    parts.append(f"    auto result = obj_.{method_name}({call_args});")
                    parts.append(f"    // 函数正常返回即通过")
                parts.append(f"}}")

                # Boundary test
                boundary_values = _generate_cpp_boundary_values(func_data)
                if params and boundary_values:
                    first_type, first_name = params[0]
                    parts.append(f"")
                    parts.append(f"TEST_F({fixture_name}, {method_name}_BoundaryValues) {{")
                    parts.append(f"    // 边界测试：{method_name} 参数 {first_name}")
                    for bv in boundary_values[:6]:
                        boundary_args_list = [_infer_cpp_default(t, n) for t, n in params]
                        if boundary_args_list:
                            boundary_args_list[0] = bv
                        boundary_args = ", ".join(boundary_args_list)
                        parts.append(f"    EXPECT_NO_THROW({{ obj_.{method_name}({boundary_args}); }});")
                    parts.append(f"}}")

                # Exception test
                if has_exception:
                    parts.append(f"")
                    parts.append(f"TEST_F({fixture_name}, {method_name}_ExceptionHandling) {{")
                    parts.append(f"    // 异常容错测试：{method_name}")
                    parts.append(f"    EXPECT_NO_THROW({{ obj_.{method_name}({call_args}); }});")
                    parts.append(f"}}")

                # Data integrity test
                if has_data_integrity:
                    parts.append(f"")
                    parts.append(f"TEST_F({fixture_name}, {method_name}_DataIntegrity) {{")
                    parts.append(f"    // 数据完整性测试：{method_name} 确定性验证")
                    parts.append(f"    auto r1 = obj_.{method_name}({call_args});")
                    parts.append(f"    auto r2 = obj_.{method_name}({call_args});")
                    parts.append(f"    // 同样输入应返回同样结果")
                    parts.append(f"}}")

    return "\n".join(parts) + "\n"


# =============================================================================
# 主入口
# =============================================================================


def main():
    parser = argparse.ArgumentParser(
        description="基于 test_cases.json 批量生成测试文件骨架"
    )
    parser.add_argument(
        "--baseline",
        default=None,
        help="基线文件路径（默认 <cwd>/test/generated_unit/test_cases.json）",
    )
    args = parser.parse_args()

    if args.baseline is None:
        baseline_path = Path.cwd() / "test" / "generated_unit" / "test_cases.json"
    else:
        baseline_path = Path(args.baseline).resolve()

    if not baseline_path.is_file():
        print(f"错误：基线文件 {baseline_path} 不存在。"
              f"请先运行 scan_repo.py --output {baseline_path} 生成基线。",
              file=sys.stderr)
        sys.exit(1)

    # 根据 baseline 路径推导 REPO_ROOT / TEST_DIR（影响 _test_path 的输出位置）
    _init_paths(baseline_path)

    with open(baseline_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    files = data.get("files", {})
    total = len(files)
    generated_py = 0
    generated_cpp = 0
    empty_cases_files = []

    for source, file_data in sorted(files.items()):
        functions = file_data.get("functions", {})
        if not functions:
            continue

        # 警告：若函数的 cases 全空,说明 Claude 尚未补齐用例描述,
        # 生成的测试骨架可能覆盖不足。
        has_any_cases = any(
            f.get("cases") for f in functions.values()
        )
        if not has_any_cases:
            empty_cases_files.append(source)

        lang = _detect_language(source)
        test_path = _test_path(source)
        test_path.parent.mkdir(parents=True, exist_ok=True)

        if lang == "cpp":
            content = generate_cpp_file(source, file_data)
            generated_cpp += 1
        else:
            content = generate_py_file(source, file_data)
            generated_py += 1

        test_path.write_text(content, encoding="utf-8")

        done = generated_py + generated_cpp
        if done % 20 == 0:
            print(f"  已生成 {done}/{total} ...")

    print(f"完成：生成 {generated_py} 个 Python 测试 + {generated_cpp} 个 C++ 测试 "
          f"= {generated_py + generated_cpp} 个文件")

    if empty_cases_files:
        print(
            f"\n提示：{len(empty_cases_files)} 个文件的所有函数 cases 均为空，"
            f"建议先让 Claude 补 cases 再重新 generate：",
            file=sys.stderr,
        )
        for f in empty_cases_files[:5]:
            print(f"  - {f}", file=sys.stderr)
        if len(empty_cases_files) > 5:
            print(f"  ... 另有 {len(empty_cases_files) - 5} 个文件",
                  file=sys.stderr)


if __name__ == "__main__":
    main()
